# Zowe API ML & Security Squad - 21PI3 Objectives (August 2021 to October 2021)


## Containerise Zowe #793

* [Containerise Zowe #793](https://github.com/zowe/zowe-install-packaging/issues/793)
Support the Zowe containerization objective for 21PI3 by completing the remaining work for the API ML.

API ML Squad Plan:
[Create APIML component images #2240](https://github.com/zowe/zowe-install-packaging/issues/2240)
[Spike: investigate methods to improve component registration in Kubernetes #2244](https://github.com/zowe/zowe-install-packaging/issues/2244)


## Password Expire Warning & Token Refresh via SAF #1601

* [Password Expire Warning & Token Refresh via SAF #1601](https://github.com/zowe/api-layer/issues/1601)
With API ML using SAF as the authentication provider a new REST API supports the change of password. The following enhancements should be implemented to the Password change facility via SAF in the APIML:
- Password expiration warning to validated/logged-on user in order to avoid a user locking out their mainframe account with too many invalid attempts
- Client must be able to refresh a 'soon to expire' token while user is logged on in order to avoid an actively engaged user being kicked out of a session

API ML Squad Plan:
Expand the range of error conditions returned to include the following:
Validated User Password is expired and needs to be changed
Validated User Password is about to expire shortly and needs to be changed
Validated User is revoked and needs to be resumed
Validated User token is near expiration (refresh/renew would be executed by the client)
Information returned on authentication error


## Zowe API ML to adopt and surface ESM's consolidated SAF Identity tokens #1390

* [Zowe API ML to adopt and surface ESM's consolidated SAF Identity tokens #1390](https://github.com/zowe/api-layer/issues/1390)
The API ML is now enabled to open access to Zowe Conformant APIs using SAF Identity JWTs that are issued, validated, and managed directly by z/OS (ESM SAF).

Current Zowe Token Providers:
- API ML generated JWT, Wrapped LTPA Token generated by z/OSMF
- z/OSMF generated liberty JWT
- API ML generated JWT on SAF direct validated credentials
All of them serve the same purpose - for APIML to provide Security Token to the client-side for sake of SSO. This enhancement will lead to Zowe API ML adopting SAF identity tokens.


## Dynamic Compression for Components #1511

* [Dynamic Compression for Components #1511](https://github.com/zowe/api-layer/issues/1511)
Add a path for ZSS, via API ML, to compress response before sending it to end-user.

API ML Squad Plan:
New component level flag to instruct API ML to buffer response from ZSS & it can perform any compression supported by modern browser on received response.


## Caching API - POC of Redis - On-platform #1192

* [HA: Caching API - POC of Redis - On-platform #1192](https://github.com/zowe/api-layer/issues/1192)
Validate whether the existing Redis solution (v5) can be used by the Caching API as an alternative on-Z storage option to VSAM. 

API ML Squad Plan:
A PoC that verifies if the Redis option is viable. Also, some performance comparison with VSAM.


## Improve testing on & off platform #1341

* [Improve testing on & off platform #1341](https://github.com/zowe/api-layer/issues/1341)
Use and update the tools created by System squad to test differing API ML configurations and improve the coverage of tests against Zowe setups. 

API ML Squad Plan:
Verified automated deployments of different configurations of the API ML based on the general Zowe tools.


## Zowe API ML Metrics dashboard MVP

* [Metrics Dashboard for ML Services #820](https://github.com/zowe/api-layer/issues/820)
Allow Tyler, the Zowe API ML administator, to track the health and performance of the API ML.
An initial Metrics Service to include basic monitoring information, relying heavily on pre-configuration given by Netflix Hystrix and Turbine.

API ML Squad Plan:
Continue supporting our mentee Saurabh as he builds out an mvp of the metrics service. 


## Simplify onboarding of the services to the API ML #1592

* [Simplify onboarding of the services to the API ML #1592](https://github.com/zowe/api-layer/issues/1592)
The onboarding of services to the API Mediation Layer is a manual, time consuming effort. There are many minor ways how to get it wrong and limited verification is available. This objective seeks to provide an intuitive and easy onboarding path that automates input where possible.

API ML Squad Plan:
The API Catalog will include a wizard to guide the user through a service onboarding procedure and based on the input provided it will generate the required and valid metadata.


## Zowe / api-layer backlog management

* [Focus on priority / high impact issues in Github](https://github.com/zowe/api-layer/labels/21PI3)
