graph TD
    subgraph Operations
        zlc[Zowe Leadership Committee - ZLC]
        packaging[Packaging]
        cicd[CI/CD]
        outreach[Outreach, Onboarding, and Conformance]
        documentation[Documentation and Website]
    end
