graph TD
    subgraph Technical Community
        ide_squad(IDE Squad<br>Lead: TBD) --- tsc[Techincal Steering Committee<br>Voting members include each squad lead, and n architects elected by the community yearly]
        clisdk_squad(CLI and SDK Squad<br>Lead: Mike Bauer) --- tsc
        appframework_squad(Desktop and ZSS Squad<br>Lead: JP Linardon) --- tsc
        apimediationlayer_squad(API Mediation Layer and Authorization/Authentication<br>Lead: Michal Supak) --- tsc
        mobile_squad[Mobile<br>Lead: TBD] --- tsc
    end
